// <auto-generated />
using System;
using LogisticaBroker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogisticaBroker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429191349_TablasIniciales")]
    partial class TablasIniciales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogisticaBroker.Models.Auditoria", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("LogisticaBroker.Models.CanalSunat", b =>
                {
                    b.Property<int>("IdCanal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCanal"));

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .IsFixedLength();

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreCanal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("IdCanal");

                    b.HasIndex("NombreCanal")
                        .IsUnique();

                    b.ToTable("CanalesSunat");
                });

            modelBuilder.Entity("LogisticaBroker.Models.ComprobantePago", b =>
                {
                    b.Property<int>("IdComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdComprobante"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaValidacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("IdDespacho")
                        .HasColumnType("integer");

                    b.Property<int?>("IdUsuarioValidador")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("text");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("IdComprobante");

                    b.HasIndex("IdDespacho");

                    b.HasIndex("IdUsuarioValidador");

                    b.ToTable("ComprobantesPago");
                });

            modelBuilder.Entity("LogisticaBroker.Models.ContratoServicio", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdContrato"));

                    b.Property<bool>("EdicionBloqueada")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoFirma")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaFirma")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TokenFirma")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UrlDocumento")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("IdContrato");

                    b.HasIndex("IdEmpresa")
                        .IsUnique();

                    b.ToTable("ContratosServicio");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Dam", b =>
                {
                    b.Property<int>("IdDam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDam"));

                    b.Property<string>("CodDocIdentificacion")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DireccionImportador")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("EdicionBloqueada")
                        .HasColumnType("boolean");

                    b.Property<string>("EmpresaTransporte")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Borrador");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Flete")
                        .HasColumnType("numeric(14,2)");

                    b.Property<int>("IdDespacho")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioCreador")
                        .HasColumnType("integer");

                    b.Property<string>("ImportadorExportador")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PuertoEmbarque")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Seguro")
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("TerminalAlmacenamiento")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("TotalAjustes")
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal>("ValorFob")
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("ViaTransporte")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Marítimo");

                    b.HasKey("IdDam");

                    b.HasIndex("IdDespacho")
                        .IsUnique();

                    b.HasIndex("IdUsuarioCreador");

                    b.ToTable("Dams");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Despacho", b =>
                {
                    b.Property<int>("IdDespacho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDespacho"));

                    b.Property<string>("CodigoBl")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoOrden")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Contenedor")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Destino")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("En proceso");

                    b.Property<DateOnly?>("Eta")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdCanal")
                        .HasColumnType("integer");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<string>("Mercancia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nave")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Origen")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short>("PorcentajeProgreso")
                        .HasColumnType("smallint");

                    b.HasKey("IdDespacho");

                    b.HasIndex("CodigoBl")
                        .IsUnique();

                    b.HasIndex("IdCanal");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Despachos");
                });

            modelBuilder.Entity("LogisticaBroker.Models.DespachoRestriccion", b =>
                {
                    b.Property<int>("IdDespacho")
                        .HasColumnType("integer");

                    b.Property<int>("IdRestriccion")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.HasKey("IdDespacho", "IdRestriccion");

                    b.HasIndex("IdRestriccion");

                    b.ToTable("DespachosRestricciones");
                });

            modelBuilder.Entity("LogisticaBroker.Models.DiligenciaAforo", b =>
                {
                    b.Property<int>("IdDiligencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDiligencia"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaProgramada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdDespacho")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("ResultadoRevision")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdDiligencia");

                    b.HasIndex("IdDespacho");

                    b.HasIndex("IdUsuario");

                    b.ToTable("DiligenciasAforo");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Documento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDocumento"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaValidacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoDoc")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioCargador")
                        .HasColumnType("integer");

                    b.Property<int?>("IdUsuarioValidador")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("IdDocumento");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdTipoDoc");

                    b.HasIndex("IdUsuarioCargador");

                    b.HasIndex("IdUsuarioValidador");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CodigoOrden")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<decimal?>("MontoItem")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Rubro")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .IsFixedLength();

                    b.HasKey("IdEmpresa");

                    b.HasIndex("CodigoOrden")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Ruc")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("LogisticaBroker.Models.EtapaDespacho", b =>
                {
                    b.Property<int>("IdEtapa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEtapa"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdDespacho")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoEtapa")
                        .HasColumnType("integer");

                    b.Property<int?>("IdUsuarioResponsable")
                        .HasColumnType("integer");

                    b.HasKey("IdEtapa");

                    b.HasIndex("IdTipoEtapa");

                    b.HasIndex("IdUsuarioResponsable");

                    b.HasIndex("IdDespacho", "IdTipoEtapa")
                        .IsUnique();

                    b.ToTable("EtapasDespacho");
                });

            modelBuilder.Entity("LogisticaBroker.Models.FotoAforo", b =>
                {
                    b.Property<int>("IdFoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFoto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdDiligencia")
                        .HasColumnType("integer");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("IdFoto");

                    b.HasIndex("IdDiligencia");

                    b.ToTable("FotosAforo");
                });

            modelBuilder.Entity("LogisticaBroker.Models.LogisticaTransporte", b =>
                {
                    b.Property<int>("IdTransporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTransporte"));

                    b.Property<string>("EmpresaTransporte")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EstadoEntrega")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaRetiro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdDespacho")
                        .HasColumnType("integer");

                    b.Property<string>("PlacaVehiculo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UrlActaRecepcion")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("IdTransporte");

                    b.HasIndex("IdDespacho")
                        .IsUnique();

                    b.ToTable("LogisticasTransporte");
                });

            modelBuilder.Entity("LogisticaBroker.Models.NotificacionEmail", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotificacion"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CorreoDestino")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EstadoEnvio")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Enviado");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioEmisor")
                        .HasColumnType("integer");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text");

                    b.Property<string>("PlantillaUsada")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdUsuarioEmisor");

                    b.ToTable("NotificacionesEmail");
                });

            modelBuilder.Entity("LogisticaBroker.Models.PartidaArancelaria", b =>
                {
                    b.Property<int>("IdPartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPartida"));

                    b.Property<int>("CantidadBultos")
                        .HasColumnType("integer");

                    b.Property<string>("DescripcionMercancias")
                        .HasColumnType("text");

                    b.Property<int>("IdDam")
                        .HasColumnType("integer");

                    b.Property<string>("PartidaNacional")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("PesoBrutoKg")
                        .HasColumnType("numeric(10,3)");

                    b.Property<decimal>("PesoNetoKg")
                        .HasColumnType("numeric(10,3)");

                    b.Property<string>("SubpartidaNaban")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdPartida");

                    b.HasIndex("IdDam");

                    b.ToTable("PartidasArancelarias");
                });

            modelBuilder.Entity("LogisticaBroker.Models.RestriccionLegal", b =>
                {
                    b.Property<int>("IdRestriccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRestriccion"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdRestriccion");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("RestriccionesLegales");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdRol");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LogisticaBroker.Models.TipoDocumento", b =>
                {
                    b.Property<int>("IdTipoDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoDoc"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("IdTipoDoc");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposDocumento");
                });

            modelBuilder.Entity("LogisticaBroker.Models.TipoEtapa", b =>
                {
                    b.Property<int>("IdTipoEtapa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoEtapa"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<short>("Orden")
                        .HasColumnType("smallint");

                    b.HasKey("IdTipoEtapa");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("Orden")
                        .IsUnique();

                    b.ToTable("TiposEtapa");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Auditoria", b =>
                {
                    b.HasOne("LogisticaBroker.Models.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LogisticaBroker.Models.ComprobantePago", b =>
                {
                    b.HasOne("LogisticaBroker.Models.Despacho", "Despacho")
                        .WithMany("Comprobantes")
                        .HasForeignKey("IdDespacho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaBroker.Models.Usuario", "UsuarioValidador")
                        .WithMany()
                        .HasForeignKey("IdUsuarioValidador")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Despacho");

                    b.Navigation("UsuarioValidador");
                });

            modelBuilder.Entity("LogisticaBroker.Models.ContratoServicio", b =>
                {
                    b.HasOne("LogisticaBroker.Models.Empresa", "Empresa")
                        .WithOne("Contrato")
                        .HasForeignKey("LogisticaBroker.Models.ContratoServicio", "IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Dam", b =>
                {
                    b.HasOne("LogisticaBroker.Models.Despacho", "Despacho")
                        .WithOne("Dam")
                        .HasForeignKey("LogisticaBroker.Models.Dam", "IdDespacho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaBroker.Models.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Despacho");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Despacho", b =>
                {
                    b.HasOne("LogisticaBroker.Models.CanalSunat", "Canal")
                        .WithMany("Despachos")
                        .HasForeignKey("IdCanal")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogisticaBroker.Models.Empresa", "Empresa")
                        .WithMany("Despachos")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Canal");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("LogisticaBroker.Models.DespachoRestriccion", b =>
                {
                    b.HasOne("LogisticaBroker.Models.Despacho", "Despacho")
                        .WithMany("Restricciones")
                        .HasForeignKey("IdDespacho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaBroker.Models.RestriccionLegal", "Restriccion")
                        .WithMany("Despachos")
                        .HasForeignKey("IdRestriccion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Despacho");

                    b.Navigation("Restriccion");
                });

            modelBuilder.Entity("LogisticaBroker.Models.DiligenciaAforo", b =>
                {
                    b.HasOne("LogisticaBroker.Models.Despacho", "Despacho")
                        .WithMany("Diligencias")
                        .HasForeignKey("IdDespacho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaBroker.Models.Usuario", "Usuario")
                        .WithMany("Diligencias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Despacho");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Documento", b =>
                {
                    b.HasOne("LogisticaBroker.Models.Empresa", "Empresa")
                        .WithMany("Documentos")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticaBroker.Models.TipoDocumento", "TipoDocumento")
                        .WithMany("Documentos")
                        .HasForeignKey("IdTipoDoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticaBroker.Models.Usuario", "UsuarioCargador")
                        .WithMany("DocumentosCargados")
                        .HasForeignKey("IdUsuarioCargador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticaBroker.Models.Usuario", "UsuarioValidador")
                        .WithMany("DocumentosValidados")
                        .HasForeignKey("IdUsuarioValidador")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empresa");

                    b.Navigation("TipoDocumento");

                    b.Navigation("UsuarioCargador");

                    b.Navigation("UsuarioValidador");
                });

            modelBuilder.Entity("LogisticaBroker.Models.EtapaDespacho", b =>
                {
                    b.HasOne("LogisticaBroker.Models.Despacho", "Despacho")
                        .WithMany("Etapas")
                        .HasForeignKey("IdDespacho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaBroker.Models.TipoEtapa", "TipoEtapa")
                        .WithMany("Etapas")
                        .HasForeignKey("IdTipoEtapa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticaBroker.Models.Usuario", "UsuarioResponsable")
                        .WithMany("EtapasResponsable")
                        .HasForeignKey("IdUsuarioResponsable")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Despacho");

                    b.Navigation("TipoEtapa");

                    b.Navigation("UsuarioResponsable");
                });

            modelBuilder.Entity("LogisticaBroker.Models.FotoAforo", b =>
                {
                    b.HasOne("LogisticaBroker.Models.DiligenciaAforo", "Diligencia")
                        .WithMany("Fotos")
                        .HasForeignKey("IdDiligencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diligencia");
                });

            modelBuilder.Entity("LogisticaBroker.Models.LogisticaTransporte", b =>
                {
                    b.HasOne("LogisticaBroker.Models.Despacho", "Despacho")
                        .WithOne("Transporte")
                        .HasForeignKey("LogisticaBroker.Models.LogisticaTransporte", "IdDespacho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despacho");
                });

            modelBuilder.Entity("LogisticaBroker.Models.NotificacionEmail", b =>
                {
                    b.HasOne("LogisticaBroker.Models.Documento", "Documento")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaBroker.Models.Usuario", "UsuarioEmisor")
                        .WithMany("NotificacionesEnviadas")
                        .HasForeignKey("IdUsuarioEmisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("UsuarioEmisor");
                });

            modelBuilder.Entity("LogisticaBroker.Models.PartidaArancelaria", b =>
                {
                    b.HasOne("LogisticaBroker.Models.Dam", "Dam")
                        .WithMany("Partidas")
                        .HasForeignKey("IdDam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dam");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Usuario", b =>
                {
                    b.HasOne("LogisticaBroker.Models.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogisticaBroker.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("LogisticaBroker.Models.CanalSunat", b =>
                {
                    b.Navigation("Despachos");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Dam", b =>
                {
                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Despacho", b =>
                {
                    b.Navigation("Comprobantes");

                    b.Navigation("Dam");

                    b.Navigation("Diligencias");

                    b.Navigation("Etapas");

                    b.Navigation("Restricciones");

                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("LogisticaBroker.Models.DiligenciaAforo", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Documento", b =>
                {
                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Empresa", b =>
                {
                    b.Navigation("Contrato");

                    b.Navigation("Despachos");

                    b.Navigation("Documentos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LogisticaBroker.Models.RestriccionLegal", b =>
                {
                    b.Navigation("Despachos");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LogisticaBroker.Models.TipoDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("LogisticaBroker.Models.TipoEtapa", b =>
                {
                    b.Navigation("Etapas");
                });

            modelBuilder.Entity("LogisticaBroker.Models.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Diligencias");

                    b.Navigation("DocumentosCargados");

                    b.Navigation("DocumentosValidados");

                    b.Navigation("EtapasResponsable");

                    b.Navigation("NotificacionesEnviadas");
                });
#pragma warning restore 612, 618
        }
    }
}
