// <auto-generated />
using LogisticaBroker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LogisticaBroker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611120000_Sprint3_ItemFactura_NuevosCampos")]
    partial class Sprint3_ItemFactura_NuevosCampos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
